sudo: required
dist: trusty

language: haxe

haxe:
  - "4.0.0-rc.2"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - haxe test.hxml


deploy:
  - provider: script
    haxe: 4.0.0-rc.2
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true